# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_register_travel_pack.ui'
#
# Created: Thu Jan 29 08:53:23 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_widget_register_travel_pack(object):
    def setupUi(self, widget_register_travel_pack):
        widget_register_travel_pack.setObjectName(_fromUtf8("widget_register_travel_pack"))
        widget_register_travel_pack.resize(589, 539)
        self.label = QtGui.QLabel(widget_register_travel_pack)
        self.label.setGeometry(QtCore.QRect(11, 21, 67, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.line_edit_user_name = QtGui.QLineEdit(widget_register_travel_pack)
        self.line_edit_user_name.setGeometry(QtCore.QRect(90, 22, 137, 22))
        self.line_edit_user_name.setObjectName(_fromUtf8("line_edit_user_name"))
        self.label_2 = QtGui.QLabel(widget_register_travel_pack)
        self.label_2.setGeometry(QtCore.QRect(11, 61, 60, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line_edit_password = QtGui.QLineEdit(widget_register_travel_pack)
        self.line_edit_password.setGeometry(QtCore.QRect(90, 60, 137, 22))
        self.line_edit_password.setEchoMode(QtGui.QLineEdit.Password)
        self.line_edit_password.setObjectName(_fromUtf8("line_edit_password"))
        self.line = QtGui.QFrame(widget_register_travel_pack)
        self.line.setGeometry(QtCore.QRect(20, 110, 531, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(widget_register_travel_pack)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 181, 191, 24))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.line_edit_origem = QtGui.QLineEdit(self.layoutWidget)
        self.line_edit_origem.setObjectName(_fromUtf8("line_edit_origem"))
        self.horizontalLayout.addWidget(self.line_edit_origem)
        self.layoutWidget1 = QtGui.QWidget(widget_register_travel_pack)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 220, 193, 24))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.line_edit_destination = QtGui.QLineEdit(self.layoutWidget1)
        self.line_edit_destination.setObjectName(_fromUtf8("line_edit_destination"))
        self.horizontalLayout_2.addWidget(self.line_edit_destination)
        self.layoutWidget2 = QtGui.QWidget(widget_register_travel_pack)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 300, 192, 24))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.date_edit_departure = QtGui.QDateEdit(self.layoutWidget2)
        self.date_edit_departure.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_edit_departure.setObjectName(_fromUtf8("date_edit_departure"))
        self.horizontalLayout_3.addWidget(self.date_edit_departure)
        self.layoutWidget3 = QtGui.QWidget(widget_register_travel_pack)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 330, 191, 24))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.date_edit_arrival = QtGui.QDateEdit(self.layoutWidget3)
        self.date_edit_arrival.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_edit_arrival.setObjectName(_fromUtf8("date_edit_arrival"))
        self.horizontalLayout_4.addWidget(self.date_edit_arrival)
        self.button_login = QtGui.QPushButton(widget_register_travel_pack)
        self.button_login.setGeometry(QtCore.QRect(310, 40, 93, 28))
        self.button_login.setObjectName(_fromUtf8("button_login"))
        self.button_register = QtGui.QPushButton(widget_register_travel_pack)
        self.button_register.setGeometry(QtCore.QRect(20, 460, 93, 28))
        self.button_register.setObjectName(_fromUtf8("button_register"))
        self.check_is_promo = QtGui.QCheckBox(widget_register_travel_pack)
        self.check_is_promo.setGeometry(QtCore.QRect(20, 390, 81, 20))
        self.check_is_promo.setObjectName(_fromUtf8("check_is_promo"))
        self.verticalLayoutWidget = QtGui.QWidget(widget_register_travel_pack)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 279, 171, 81))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlayout_guests = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout_guests.setMargin(0)
        self.vlayout_guests.setObjectName(_fromUtf8("vlayout_guests"))
        self.buton_add_guest = QtGui.QPushButton(widget_register_travel_pack)
        self.buton_add_guest.setGeometry(QtCore.QRect(450, 200, 93, 28))
        self.buton_add_guest.setObjectName(_fromUtf8("buton_add_guest"))
        self.widget = QtGui.QWidget(widget_register_travel_pack)
        self.widget.setGeometry(QtCore.QRect(280, 200, 144, 24))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.combo_age = QtGui.QComboBox(self.widget)
        self.combo_age.setObjectName(_fromUtf8("combo_age"))
        self.horizontalLayout_5.addWidget(self.combo_age)
        self.widget1 = QtGui.QWidget(widget_register_travel_pack)
        self.widget1.setGeometry(QtCore.QRect(9, 260, 187, 24))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.widget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.combo_number_of_rooms = QtGui.QComboBox(self.widget1)
        self.combo_number_of_rooms.setObjectName(_fromUtf8("combo_number_of_rooms"))
        self.horizontalLayout_6.addWidget(self.combo_number_of_rooms)

        self.retranslateUi(widget_register_travel_pack)
        QtCore.QMetaObject.connectSlotsByName(widget_register_travel_pack)

    def retranslateUi(self, widget_register_travel_pack):
        widget_register_travel_pack.setWindowTitle(_translate("widget_register_travel_pack", "Register travel pack", None))
        self.label.setText(_translate("widget_register_travel_pack", "User name:", None))
        self.label_2.setText(_translate("widget_register_travel_pack", "Password:", None))
        self.label_3.setText(_translate("widget_register_travel_pack", "Origin:", None))
        self.label_4.setText(_translate("widget_register_travel_pack", "Destination:", None))
        self.label_5.setText(_translate("widget_register_travel_pack", "Departure date:", None))
        self.label_6.setText(_translate("widget_register_travel_pack", "Arrival date:", None))
        self.button_login.setText(_translate("widget_register_travel_pack", "Log in", None))
        self.button_register.setText(_translate("widget_register_travel_pack", "Register", None))
        self.check_is_promo.setText(_translate("widget_register_travel_pack", "Is Promo", None))
        self.buton_add_guest.setText(_translate("widget_register_travel_pack", "add guest", None))
        self.label_8.setText(_translate("widget_register_travel_pack", "Guest age:", None))
        self.label_7.setText(_translate("widget_register_travel_pack", "Number of rooms:", None))

