# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_register_plane_ticket.ui'
#
# Created: Mon Feb  2 17:13:50 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_widget_register_plane_ticket(object):
    def setupUi(self, widget_register_plane_ticket):
        widget_register_plane_ticket.setObjectName(_fromUtf8("widget_register_plane_ticket"))
        widget_register_plane_ticket.resize(589, 539)
        self.button_register = QtGui.QPushButton(widget_register_plane_ticket)
        self.button_register.setGeometry(QtCore.QRect(19, 469, 93, 28))
        self.button_register.setObjectName(_fromUtf8("button_register"))
        self.line_edit_user_name = QtGui.QLineEdit(widget_register_plane_ticket)
        self.line_edit_user_name.setGeometry(QtCore.QRect(89, 31, 137, 22))
        self.line_edit_user_name.setObjectName(_fromUtf8("line_edit_user_name"))
        self.layoutWidget = QtGui.QWidget(widget_register_plane_ticket)
        self.layoutWidget.setGeometry(QtCore.QRect(279, 209, 144, 24))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.combo_age = QtGui.QComboBox(self.layoutWidget)
        self.combo_age.setObjectName(_fromUtf8("combo_age"))
        self.horizontalLayout_5.addWidget(self.combo_age)
        self.button_login = QtGui.QPushButton(widget_register_plane_ticket)
        self.button_login.setGeometry(QtCore.QRect(309, 49, 93, 28))
        self.button_login.setObjectName(_fromUtf8("button_login"))
        self.line_edit_password = QtGui.QLineEdit(widget_register_plane_ticket)
        self.line_edit_password.setGeometry(QtCore.QRect(89, 69, 137, 22))
        self.line_edit_password.setEchoMode(QtGui.QLineEdit.Password)
        self.line_edit_password.setObjectName(_fromUtf8("line_edit_password"))
        self.layoutWidget_2 = QtGui.QWidget(widget_register_plane_ticket)
        self.layoutWidget_2.setGeometry(QtCore.QRect(9, 190, 191, 24))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.line_edit_origem = QtGui.QLineEdit(self.layoutWidget_2)
        self.line_edit_origem.setObjectName(_fromUtf8("line_edit_origem"))
        self.horizontalLayout.addWidget(self.line_edit_origem)
        self.check_only_departure = QtGui.QCheckBox(widget_register_plane_ticket)
        self.check_only_departure.setGeometry(QtCore.QRect(19, 399, 111, 20))
        self.check_only_departure.setObjectName(_fromUtf8("check_only_departure"))
        self.verticalLayoutWidget = QtGui.QWidget(widget_register_plane_ticket)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(279, 288, 171, 81))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlayout_guests = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlayout_guests.setMargin(0)
        self.vlayout_guests.setObjectName(_fromUtf8("vlayout_guests"))
        self.line = QtGui.QFrame(widget_register_plane_ticket)
        self.line.setGeometry(QtCore.QRect(19, 119, 531, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget_3 = QtGui.QWidget(widget_register_plane_ticket)
        self.layoutWidget_3.setGeometry(QtCore.QRect(9, 339, 191, 24))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.date_edit_arrival = QtGui.QDateEdit(self.layoutWidget_3)
        self.date_edit_arrival.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_edit_arrival.setObjectName(_fromUtf8("date_edit_arrival"))
        self.horizontalLayout_4.addWidget(self.date_edit_arrival)
        self.layoutWidget_4 = QtGui.QWidget(widget_register_plane_ticket)
        self.layoutWidget_4.setGeometry(QtCore.QRect(9, 229, 193, 24))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.line_edit_destination = QtGui.QLineEdit(self.layoutWidget_4)
        self.line_edit_destination.setObjectName(_fromUtf8("line_edit_destination"))
        self.horizontalLayout_2.addWidget(self.line_edit_destination)
        self.layoutWidget_5 = QtGui.QWidget(widget_register_plane_ticket)
        self.layoutWidget_5.setGeometry(QtCore.QRect(9, 309, 192, 24))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.date_edit_departure = QtGui.QDateEdit(self.layoutWidget_5)
        self.date_edit_departure.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_edit_departure.setObjectName(_fromUtf8("date_edit_departure"))
        self.horizontalLayout_3.addWidget(self.date_edit_departure)
        self.label = QtGui.QLabel(widget_register_plane_ticket)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.buton_add_guest = QtGui.QPushButton(widget_register_plane_ticket)
        self.buton_add_guest.setGeometry(QtCore.QRect(449, 209, 93, 28))
        self.buton_add_guest.setObjectName(_fromUtf8("buton_add_guest"))
        self.layoutWidget_6 = QtGui.QWidget(widget_register_plane_ticket)
        self.layoutWidget_6.setGeometry(QtCore.QRect(8, 269, 187, 24))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.combo_number_of_rooms = QtGui.QComboBox(self.layoutWidget_6)
        self.combo_number_of_rooms.setObjectName(_fromUtf8("combo_number_of_rooms"))
        self.horizontalLayout_6.addWidget(self.combo_number_of_rooms)
        self.label_2 = QtGui.QLabel(widget_register_plane_ticket)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 60, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))

        self.retranslateUi(widget_register_plane_ticket)
        QtCore.QMetaObject.connectSlotsByName(widget_register_plane_ticket)

    def retranslateUi(self, widget_register_plane_ticket):
        widget_register_plane_ticket.setWindowTitle(_translate("widget_register_plane_ticket", "Register plane ticket", None))
        self.button_register.setText(_translate("widget_register_plane_ticket", "Register", None))
        self.label_8.setText(_translate("widget_register_plane_ticket", "Guest age:", None))
        self.button_login.setText(_translate("widget_register_plane_ticket", "Log in", None))
        self.label_3.setText(_translate("widget_register_plane_ticket", "Origin:", None))
        self.check_only_departure.setText(_translate("widget_register_plane_ticket", "Only departure", None))
        self.label_6.setText(_translate("widget_register_plane_ticket", "Arrival date:", None))
        self.label_4.setText(_translate("widget_register_plane_ticket", "Destination:", None))
        self.label_5.setText(_translate("widget_register_plane_ticket", "Departure date:", None))
        self.label.setText(_translate("widget_register_plane_ticket", "User name:", None))
        self.buton_add_guest.setText(_translate("widget_register_plane_ticket", "add guest", None))
        self.label_7.setText(_translate("widget_register_plane_ticket", "Number of rooms:", None))
        self.label_2.setText(_translate("widget_register_plane_ticket", "Password:", None))

